### ISSUE TITLE
Allow global namespace kill settings

### ISSUE THREAD

**Issue by gjcarneiro** [asobti/kube-monkey#135]
My app has many many deployments, it would be tedious to have to modify all of them.

Can we instead have some annotations on a namespace.  I'd like my dev namespace to just randomly kill pods.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: my-dev-namespace
  # add kube-monkey labels as usual, they will apply to everything inside the namespace
  labels:
    kube-monkey/enabled: enabled
    kube-monkey/identifier: monkey-victim
    kube-monkey/mtbf: '2'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: 1
```
