### ISSUE TITLE
Doesn't understand OpenShift Deployment Configuration

### ISSUE THREAD

**Issue by alberttwong** [asobti/kube-monkey#138]
Figured out how to deploy on openshift.   Problem now is that that kube-monkey only understands deployment and not openshift's enhanced version of kube deployment called deployment configuration.

**Comment by alberttwong** [comment]
```
W0115 16:00:00.063723       1 factory.go:46] Failed to fetch eligible deployments for namespace  due to error: deployments.apps is forbidden: User "system:serviceaccount:kube-system:default" cannot list deployments.apps at the cluster scope: User "system:serviceaccount:kube-system:default" cannot list all deployments.apps in the cluster
```

**Comment by faust64** [comment]
According to that error message, you're either missing a rolebinding, or aren't using your serviceaccount starting your Pod.

FYI, running on OpenShift, I've been using the following template:

```
apiVersion: v1
kind: Template
metadata:
  name: kube-monkey
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${MONKEY_NAME}
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: ${MONKEY_NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    name: ${MONKEY_NAME}
    namespace: ${MONKEY_NAMESPACE}
- apiVersion: v1
  data:
    config.toml: |
      [kubemonkey]
      run_hour = 8
      start_hour = 10
      end_hour = 16
      blacklisted_namespaces = [ "default", "kube-service-catalog", "kube-system", "openshift-console", "openshift-infra", "openshift-logging", "openshift-metrics-server", "openshift-monitoring", "openshift-node", "openshift-sdn", "openshift-web-console", "${MONKEY_NAMESPACE}" ]
      time_zone = "Europe/Paris"
  kind: ConfigMap
  metadata:
    name: ${MONKEY_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${MONKEY_NAME}
  spec:
    replicas: 1
    selector:
      name: ${MONKEY_NAME}
    template:
      metadata:
        labels:
          name: ${MONKEY_NAME}
      spec:
        containers:
        - args: ["-v=5", "-log_dir=/var/log/kube-monkey"]
          command: [ "/kube-monkey" ]
          image: ${MONKEY_IMAGE}
          name: monkey
          volumeMounts:
          - name: config-volume
            mountPath: /etc/kube-monkey
          - name: logs-volume
            mountPath: /var/log/kube-monkey
        serviceAccount: ${MONKEY_NAME}
        serviceAccountName: ${MONKEY_NAME}
        volumes:
        - configMap:
            name: ${MONKEY_NAME}
          name: config-volume
        - emptyDir: {}
          name: logs-volume
parameters:
- name: MONKEY_IMAGE
  value: ayushsobti/kube-monkey:v0.3.0
- name: MONKEY_NAME
  value: kube-monkey
- name: MONKEY_NAMESPACE
  value: monkeypaw
```

Now we could raise the issue that kube-monkey isn't able to process deploymentconfigs.

I've been duplicating `victims/factory/deployments` into `victims/factory/deploymentconfigs`, fixing whatever needed to be, ... now I'm trying to figure out how to patch `vendor/k8s.io/api`, as I'm looking at generated code, still unsure where that came from
```
# make build
which: no golangci-lint in (./bin)
rm -f kube-monkey
find . -path ./vendor -prune -o -name '*.go' -print | xargs -L 1 -I % gofmt -s -w %
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o kube-monkey
# github.com/asobti/kube-monkey/victims/factory/deploymentconfigs
victims/factory/deploymentconfigs/deploymentconfigs.go:18:15: undefined: "github.com/asobti/kube-monkey/vendor/k8s.io/api/apps/v1".DeploymentConfig
victims/factory/deploymentconfigs/deploymentconfigs.go:37:27: undefined: "github.com/asobti/kube-monkey/vendor/k8s.io/api/apps/v1".DeploymentConfig
victims/factory/deploymentconfigs/deploymentconfigs.go:47:40: undefined: "github.com/asobti/kube-monkey/vendor/k8s.io/api/apps/v1".DeploymentConfig
victims/factory/deploymentconfigs/eligible_deploymentconfigs.go:21:43: clientset.AppsV1().DeploymentConfigs undefined (type "github.com/asobti/kube-monkey/vendor/k8s.io/client-go/kubernetes/typed/apps/v1".AppsV1Interface has no field or method DeploymentConfigs)
victims/factory/deploymentconfigs/eligible_deploymentconfigs.go:50:45: clientset.AppsV1().DeploymentConfigs undefined (type "github.com/asobti/kube-monkey/vendor/k8s.io/client-go/kubernetes/typed/apps/v1".AppsV1Interface has no field or method DeploymentConfigs)
victims/factory/deploymentconfigs/eligible_deploymentconfigs.go:59:45: clientset.AppsV1().DeploymentConfigs undefined (type "github.com/asobti/kube-monkey/vendor/k8s.io/client-go/kubernetes/typed/apps/v1".AppsV1Interface has no field or method DeploymentConfigs)
victims/factory/deploymentconfigs/eligible_deploymentconfigs.go:74:45: clientset.AppsV1().DeploymentConfigs undefined (type "github.com/asobti/kube-monkey/vendor/k8s.io/client-go/kubernetes/typed/apps/v1".AppsV1Interface has no field or method DeploymentConfigs)
make: *** [build] Error 2
```
