### ISSUE TITLE
kube-monkey schedules Termination successfully, but POD always doesn't be killed 

### ISSUE THREAD

**Issue by douxiaoniu77** [asobti/kube-monkey#193]
Here is the kube-monkey pod logs:
I0730 02:48:36.817408       1 config.go:82] Successfully validated configs
I0730 02:48:36.817626       1 main.go:54] Starting kube-monkey with v logging level 5 and local log directory /var/log/kube-monkey
I0730 02:48:36.826158       1 kubemonkey.go:24] Status Update: Generating next schedule at 2020-07-30 11:00:00 +0800 CST
I0730 03:00:00.000513       1 schedule.go:64] Status Update: Generating schedule for terminations
I0730 03:00:00.052242       1 schedule.go:57] Status Update: 1 terminations scheduled today
I0730 03:00:00.052316       1 schedule.go:59] v1.Deployment nginx-deployment scheduled for termination at 07/30/2020 12:41:00 +0800 CST
I0730 03:00:00.052340       1 kubemonkey.go:62] Status Update: Waiting to run scheduled terminations.
	********** Today's schedule **********
	k8 Api Kind	Kind Name		Termination Time
	-----------	---------		----------------
	v1.Deployment	nginx-deployment		07/30/2020 12:41:00 +0800 CST
	********** End of schedule **********

Here is the config for kube-monkey pod
![image](https://user-images.githubusercontent.com/56914951/88877252-a3c7f600-d257-11ea-8cfb-a1ae1a00eb92.png)

config for deployment set to be killed by kube-monkey
![image](https://user-images.githubusercontent.com/56914951/88877303-ba6e4d00-d257-11ea-847a-4130bc184fc1.png)

**Comment by kyrylyuk-andriy** [comment]
I have the same issue, deployments are scheduled to be terminated but not all of them actually were terminated (pods in a deployment)

**Comment by worldtiki** [comment]
Can you share the configs for kube monkey that you are using?

**Comment by kyrylyuk-andriy** [comment]
my kube-monkey tool config 

```
config:
  dryRun: false
  runHour: 11
  startHour: 12
  endHour: 13
  blacklistedNamespaces: [ "kube-system", "istio-system", "rbac-manager", "db-migrate" ]
  whitelistedNamespaces: [ "default"]
  timeZone: America/New_York
  debug:
   enabled: false # if you want to enable debugging and see how pods killed immediately set this to true
   schedule_immediate_kill: false
```

and labels in each opted in service 

```
metadata:
  labels:
    kube-monkey/enabled: enabled
    kube-monkey/identifier: kube-monkey-victim
    kube-monkey/kill-mode: fixed
    kube-monkey/kill-value: "3"
    kube-monkey/mtbf: "1"
spec:
  template:
    metadata:
      labels:
        kube-monkey/enabled: enabled
        kube-monkey/identifier: kube-monkey-victim
 ```

this labels config use around 10-12 different services, all of them were scheduled for termination with pre defined hours  and only 3-4 services (pods) were actually were terminated,
