### ISSUE TITLE
How to pull from a private docker registry?

### ISSUE THREAD

**Issue by Gaethje** [asobti/kube-monkey#239]
From Helm chart,
```
image:
  repository: ayushsobti/kube-monkey
  tag: v0.5.0
  pullPolicy: IfNotPresent
```
My k8 cluster is on-prem vanilla without any internet connection. we pull images from a private docker registry. How to pull from private docker registry instead of docker.io? 
in other application's helm chart (ex. litmus chaos) it's available so we pull like this ->
```
  image:
    registry: klstg-docker.slb-wartifactory-v.stg.kdh.local
    repository: litmus-chaos/bitnami/mongodb-exporter
    tag: latest
    pullPolicy: IfNotPresent
```
