### ISSUE TITLE
podSecurityContext does not work using Helm values template

### ISSUE THREAD

**Issue by lisenet** [asobti/kube-monkey#254]
Using Helm [values.yaml](https://github.com/asobti/kube-monkey/blob/master/helm/kubemonkey/values.yaml#L64) file to set `podSecurityContext` following commit [a034c94](https://github.com/asobti/kube-monkey/commit/a034c9456ed301396bc05206c85181819af59dfa) does not seem to work.

## Attempt 1

Snippet from the `values.yaml` that is in use when the problem happens:

```yaml
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
```

The following error appears:

```
Failed to open custom log directory at /var/log/kube-monkey; defaulting to /tmp! Error: mkdir /var/log: permission denied
```

Fair enough, the user may not have privileges to write to `/var/log`. 

## Attempt 2

Updating `values.yaml` file to point container to the `/tmp` directory for logs where it **should** be able to write to:

```yaml
args:
  logLevel: 5
  logDir: /tmp/kube-monkey

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
```

Another error appears, the container can't create `/tmp/kube-monkey/`:

```
Failed to open custom log directory at /tmp/kube-monkey; defaulting to /tmp! Error: mkdir /tmp: permission denied
```

## Attempt 3

Another update to the `values.yaml` file to remove `/tmp` from the path:

```yaml
args:
  logLevel: 5
  logDir: /kube-monkey

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
```

The error:

```
Failed to open custom log directory at /tmp; defaulting to /tmp! Error: mkdir /tmp: permission denied
```

If it's defaulting to `/tmp`, why does it attempt to create `/tmp`?

## Attempt 4

Going for plain `/` for the `logDir` this time:

```yaml
args:
  logLevel: 5
  logDir: /

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
```

The error:

```
log: exiting because of error: log: cannot create log: open /tmp/kube-monkey.kubemonkey-kube-monkey-56fb8ccbbf-ww8q6.unknownuser.log.INFO.20230803-141834.1: no such file or directory
```

## Question

Was this merged without being tested? Can you post a working example of the Helm `values.file`?
