### ISSUE TITLE
No terminations scheduled issue

### ISSUE THREAD

**Issue by dcuestam** [asobti/kube-monkey#80]
Hi, I have been some days trying to use kube-monkey in order to kill pods of a namespace but all the tries are not being succesfull. Every time I try a configuration, I receive the next message : 
	********** Today's schedule **********
No terminations scheduled
	********** End of schedule *********

I don't understand what is happening, those are my configuration files:

deployment.yml: 

```
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: kube-monkey
    namespace: kube-system
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          kube-monkey/enabled: enabled
          kube-monkey/identifier: ignite-10
          kube-monkey/mtbf: '2'
          kube-monkey/kill-mode: "fixed"
          kube-monkey/kill-value: "1"
      spec:
        containers:
          -  name: kube-monkey
             command:
               - "/kube-monkey"
             args: ["-v=5", "-log_dir=/var/log/kube-monkey"]
             image: ayushsobti/kube-monkey:v0.2.3
             volumeMounts:
               - name: config-volume
                 mountPath: "/etc/kube-monkey"
        volumes:
          - name: config-volume
            configMap:
              name: kube-monkey-config-map
```
And configmap.yaml:

```
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kube-monkey-config-map
    namespace: kube-system
  data:
    config.toml: |
      [kubemonkey]
      run_hour = 11
      start_hour = 12
      end_hour = 13
      blacklisted_namespaces = ["kube-system"]
      whitelisted_namespaces = [] # I have tried using "ignite" here, which is the namespace that I want to for kill pods
      time_zone="Europe/Madrid"
```
Those are the pods that I have in the ignite namespace: 
<img width="1663" alt="captura de pantalla 2018-07-09 a las 11 09 05" src="https://user-images.githubusercontent.com/36133262/42441507-9f486d3e-8368-11e8-9959-0690b8a4ce19.png">

This is the kube-system namespace:

<img width="1666" alt="captura de pantalla 2018-07-09 a las 11 09 16" src="https://user-images.githubusercontent.com/36133262/42441516-a90d8016-8368-11e8-8b67-73e2f33c61ce.png">

This is the log of the kube-monkey:
<img width="1653" alt="captura de pantalla 2018-07-09 a las 11 09 32" src="https://user-images.githubusercontent.com/36133262/42441528-b42e24f0-8368-11e8-9ca8-b608e97beb3b.png">

Please, could anyone help me?
