### ISSUE TITLE
Example deployment.yaml fails to start kube monkey

### ISSUE THREAD

**Issue by arun-gupta** [asobti/kube-monkey#83]
0.2.3 is the only tag available at DockerHub:

![image](https://user-images.githubusercontent.com/113947/42545191-53b103e6-846b-11e8-9551-f10723ef51f3.png)

0.1.0 tag not available on DockerHub. As a result, https://github.com/asobti/kube-monkey/blob/master/examples/deployment.yaml#L19 fails to start kube monkey with the following error:

```
kube-monkey-d46b987b9-lrg67                                           0/1       ImagePullBackOff   0          1m
```

Also, the image's repo name needs to be specified as well.

The updated `deployment.yaml` that works is:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-monkey
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-monkey
    spec:
      containers:
        -  name: kube-monkey
           command:
             - "/kube-monkey"
           args: ["-v=5", "-log_dir=/var/log/kube-monkey"]
           image: ayushsobti/kube-monkey:v0.2.3
           volumeMounts:
             - name: config-volume
               mountPath: "/etc/kube-monkey"
      volumes:
        - name: config-volume
          configMap:
            name: kube-monkey-config-map
```
